server:
  port: 8443   #port number
spring:
  datasource:   #database
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/commute?serverTimezone=GMT%2B8
    username: root
    password: 123456
#  redis:
#    host: 192.168.99.100
#    port: 6379
#    pcmassword:
#    jedis:
#      pool:
#        max-idle: 8
#        min-idle: 0
#        max-active: 8
#        max-wait: -1ms
mybatis:
  type-aliases-package: com.elec5620.commute.pojo
  mapper-locations: classpath:Mapper/*.xml
commute:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5
    expire: 604800
    header: Authorization

shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379